### ISSUE TITLE
Compatibility issues on CN360 servers

### ISSUE THREAD

**Issue by shencore** [AndrewTaro/MinimapSubPingerPublic#3]
Hello, I'm a player from CN360 server, I've been using your mod for the past year and it's been a very great help to me, after the 13.2.0 update I also updated to the latest version of the mod in time, but found that it doesn't work properly. After uninstalling all mods and testing, it was confirmed that it was this mod that may not be compatible with my client, here is my python log, I would like your help in locating where the problem is.

[Aslains_WoWs_Logs.zip](https://github.com/AndrewTaro/MinimapSubPingerPublic/files/14822494/Aslains_WoWs_Logs.zip)

**Comment by AndrewTaro** [comment]
Hi, Thanks for sharing the information. I'll look into it.

**Comment by AndrewTaro** [comment]
Update: I checked the logs, but the mod wasn't even loaded. If it was successful there should've been a log like this:
`[MinimapSubPinger, ModsAPI] Successfully replaced a function.`

This seems to be the issue with the API authentication, and I think the devs need to fix it.  
I'll contact WG but it may take a while. (It is possible they are not responsible for the CN client..)

**Comment by shencore** [comment]
Thanks, the MOD is working fine in version 13.3, thank you very much for your work!

**Comment by AndrewTaro** [comment]
Glad it worked!
